title: Ghosthood
description: The Dossier Vault
url: "https://sysgit9.github.io"
baseurl: "/ghosthood-site"
theme: minima
collections:
  dossiers:
    output: true
    permalink: /vault/:title/
defaults:
  - scope: { path: "", type: dossiers }
    values: { layout: dossier }
